branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: banking
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: ap-south-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
